#
# https://artifacthub.io/packages/helm/bitnami/mlflow
# https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml
#
#
tracking:
  service:
    type: LoadBalancer

  # temporary user / pass here, should be in the secret
  auth:
    enabled: true
    username: user
    password: "6440921D-2493-42AA-BE40-428CD753D81D"

run:
  enabled: false

minio:
  enabled: true
  auth:
    rootUser: "mlflow"
    rootPassword: "mlflow123secure"
  defaultBuckets: "mlflow"
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
      
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "do-block-storage"

postgresql:
  enabled: true
  auth:
    postgresPassword: "mlflow123secure"
    database: "mlflow"
    username: "mlflow"
    password: "mlflow123secure"
      
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "do-block-storage"

# Using default image from Helm chart

