# Secret for MLflow to access MinIO
# This will be created with actual credentials during deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AccessKeyID: minioadmin
  SecretKey: minioadmin123
