# MLflow Production Values for Digital Ocean Kubernetes
# Configured to use SQLite and MinIO (simplified working version)
# Optimized for limited cluster resources - using SQLite to avoid DB issues
#
# Chart: https://artifacthub.io/packages/helm/bitnami/mlflow
# Values: https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml

# MLflow tracking server configuration
tracking:
  service:
    type: LoadBalancer
    port: 5000

  # Disable authentication to simplify deployment
  auth:
    enabled: false

  # Reduced resources for tracking server
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  # Disable horizontal pod autoscaling to save resources
  autoscaling:
    enabled: false

# Disable MLflow's bundled services
run:
  enabled: false

minio:
  enabled: false

postgresql:
  enabled: false

# Disable external PostgreSQL - use SQLite fallback
# externalDatabase:
#   dialectDriver: "postgresql"
#   host: "risingwave-postgresql.risingwave.svc.cluster.local"
#   port: 5432
#   user: mlflow
#   database: mlflow
#   password: mlflow

# Use external MinIO from RisingWave
externalS3:
  host: "risingwave-minio.risingwave.svc.cluster.local"
  port: 9000
  useCredentialsInSecret: true
  existingSecret: "mlflow-minio-secret"
  existingSecretAccessKeyIDKey: "AccessKeyID"
  existingSecretKeySecretKey: "SecretKey"
  protocol: "http"
  bucket: "mlflow-d971"
  serveArtifacts: true

# Persistence for MLflow data (SQLite will be stored here)
persistence:
  enabled: true
  size: 10Gi
  storageClass: "do-block-storage"

# Service account
serviceAccount:
  create: true
  name: mlflow

# Pod security context
podSecurityContext:
  enabled: true
  fsGroup: 1001

# Container security context
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

# Liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
