#
# https://kubernetes.io/docs/concepts/configuration/secret/
#
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AccessKeyID: iRxL7iFBcwu7IbtL13Z6
  SecretKey: VZiZVpcvh9M18EloURWr1k8k0s1dSxEE4fLJ4Oju