apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ../../manifests/services/trades
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/mdshihabullah/real-time-crypto-price-predictor/trades:beta-08-06-2025-11-14-2caeb5f
  target:
    group: apps
    version: v1
    kind: Deployment
    name: trades
