{
 "title": "Crypto Currency Price",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "SOL/EUR",
   "type": "candlestick",
   "description": "Candle chart for ETH/EUR only",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  pair, open, high, low, close, window_start_ms, window_end_ms, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'SOL/EUR';"
    }
   ]
  },
  {
   "title": "ETH/EUR",
   "type": "candlestick",
   "description": "Candle chart for ETH/EUR only",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  pair, open, high, low, close, window_start_ms, window_end_ms, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'ETH/EUR';"
    }
   ]
  },
  {
   "title": "BTC/EUR",
   "type": "candlestick",
   "description": "Candle chart for BTC/EUR only",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  pair, open, high, low, close, window_start_ms, window_end_ms, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'BTC/EUR';"
    }
   ]
  }
 ]
}