{
 "title": "Technical Indicators",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "On-Balance Volume (OBV) for ETH/EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  obv, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'ETH/EUR';"
    }
   ]
  },
  {
   "title": "Simple Moving Average (SMA) for ETH/EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  sma_7,sma_14, sma_21, sma_60, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'ETH/EUR';"
    }
   ]
  },
  {
   "title": "Exponential Moving Average (EMA) for ETH/EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  ema_7,ema_14, ema_21, ema_60, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'ETH/EUR';"
    }
   ]
  },
  {
   "title": "Moving Average Convergence Divergence (MACD) for ETH/EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  macd_7,macd_14, macd_21, macd_60, macdsignal_7, macdsignal_14, macdsignal_21, macdsignal_60, to_timestamp(window_start_ms/1000) as time\nFROM\n  public.technical_indicators\nWHERE\n  pair= 'ETH/EUR';"
    }
   ]
  }
 ]
}