---
# Candles Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: candles
  namespace: services
---
apiVersion: v1
kind: Service
metadata:
  name: candles
  namespace: services
spec:
  selector:
    app: candles
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      serviceAccountName: candles
      initContainers:
      - name: init-state-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/state && chmod 777 /app/state']
        volumeMounts:
        - name: state-volume
          mountPath: /app/state
      containers:
      - name: candles
        image: ${CANDLES_IMAGE}
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: "crypto-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles-consumer-group"
        - name: WINDOW_IN_SEC
          value: "60"
        - name: EMIT_INTERMEDIATE_CANDLES
          value: "True"
        - name: LOG_LEVEL
          value: "INFO"
        - name: STATE_DIR
          value: "/app/state"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: state-volume
          mountPath: /app/state
        ports:
        - containerPort: 8000
      volumes:
      - name: state-volume
        emptyDir: {}
