apiVersion: v1
kind: Secret
metadata:
  name: predictor-training-secrets
  namespace: services
type: Opaque
stringData:
  # MLflow tracking credentials - replace with actual production values
  mlflow_tracking_username: "user"
  mlflow_tracking_password: "6440921D-2493-42AA-BE40-428CD753D81D"
  
  # MinIO credentials (for direct artifact access)
  minio_access_key: "minioadmin"
  minio_secret_key: "minioadmin123secure"
  
  # Additional sensitive configuration can be added here
  # These should be injected via CI/CD pipeline in real deployment 