CREATE TABLE IF NOT EXISTS technical_indicators (
    pair VARCHAR,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    window_start_ms BIGINT,
    window_end_ms BIGINT,
    window_in_sec INTEGER,
    sma_7 DOUBLE PRECISION,
    ema_7 DOUBLE PRECISION,
    rsi_7 DOUBLE PRECISION,
    adx_7 DOUBLE PRECISION,
    macd_7 DOUBLE PRECISION,
    macdsignal_7 DOUBLE PRECISION,
    macdhist_7 DOUBLE PRECISION,
    sma_14 DOUBLE PRECISION,
    ema_14 DOUBLE PRECISION,
    rsi_14 DOUBLE PRECISION,
    adx_14 DOUBLE PRECISION,
    macd_14 DOUBLE PRECISION,
    macdsignal_14 DOUBLE PRECISION,
    macdhist_14 DOUBLE PRECISION,
    sma_21 DOUBLE PRECISION,
    ema_21 DOUBLE PRECISION,
    rsi_21 DOUBLE PRECISION,
    adx_21 DOUBLE PRECISION,
    macd_21 DOUBLE PRECISION,
    macdsignal_21 DOUBLE PRECISION,
    macdhist_21 DOUBLE PRECISION,
    sma_60 DOUBLE PRECISION,
    ema_60 DOUBLE PRECISION,
    rsi_60 DOUBLE PRECISION,
    adx_60 DOUBLE PRECISION,
    macd_60 DOUBLE PRECISION,
    macdsignal_60 DOUBLE PRECISION,
    macdhist_60 DOUBLE PRECISION,
    obv DOUBLE PRECISION,
    created_at TIMESTAMPTZ,
    PRIMARY KEY (pair, window_start_ms, window_end_ms)
) WITH (
    connector='kafka',
    topic='technical_indicators',
    properties.bootstrap.server='kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092'
) FORMAT PLAIN ENCODE JSON;