---
# Trades Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trades
  namespace: services
---
apiVersion: v1
kind: Service
metadata:
  name: trades
  namespace: services
spec:
  selector:
    app: trades
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      serviceAccountName: trades
      containers:
      - name: trades
        image: ${TRADES_IMAGE}
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: crypto-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"
        - name: LOG_LEVEL
          value: "INFO"
        - name: STATE_DIR
          value: "/app/state"
        volumeMounts:
        - name: trades-data
          mountPath: /app/state
        ports:
        - containerPort: 8000
      volumes:
      - name: trades-data
        persistentVolumeClaim:
          claimName: trades-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trades-data
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage 