apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
  namespace: services
  labels:
    app: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      # Initialize container to set up directories with correct permissions
      initContainers:
      - name: init-dirs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/drift_reports /app/reports && chmod -R 777 /app/drift_reports /app/reports']
        volumeMounts:
        - name: reports-volume
          mountPath: /app/drift_reports
        - name: reports-volume
          mountPath: /app/reports
      containers:
      - name: predictor
        image: predictor:dev
        imagePullPolicy: Never # Use the local image
        envFrom:
        - configMapRef:
            name: predictor-config
        - secretRef:
            name: predictor-mlflow-credentials
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: reports-volume
          mountPath: /app/drift_reports
        - name: reports-volume
          mountPath: /app/reports
      volumes:
      - name: reports-volume
        # For development, use emptyDir
        emptyDir: {}
