apiVersion: apps/v1
kind: Deployment
metadata:
  name: structurizr-lite
  namespace: structurizr
  labels:
    app: structurizr-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: structurizr-lite
  template:
    metadata:
      labels:
        app: structurizr-lite
    spec:
      containers:
      - name: structurizr-lite
        image: structurizr:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: structurizr-lite-svc
  namespace: structurizr
spec:
  selector:
    app: structurizr-lite
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30089
  type: NodePort
