# Kafka Topics
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: trades
  namespace: kafka
  labels:
    strimzi.io/cluster: crypto-kafka-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824  # 1 GB
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: candles
  namespace: kafka
  labels:
    strimzi.io/cluster: crypto-kafka-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824  # 1 GB
# Kafka UI with LoadBalancer service
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
