#
#  https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
#
#  kustomize build deployments/dev/technical_indicators | kubectl apply -f -
#
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./technical_indicators.yaml

commonLabels:
  app.kubernetes.io/name: technical-indicators
  app.kubernetes.io/part-of: real-time-crypto-price-predictor
