apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ../../manifests/services/technical_indicators
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/mdshihabullah/real-time-crypto-price-predictor/technical_indicators:beta-30-05-2025-2da7526
  target:
    group: apps
    version: v1
    kind: Deployment
    name: technical-indicators
